name: Bug Report
description: Report a bug in ring-mqtt
title: 'Bug: <Please enter bug description here>'
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search [all open/closed issues](https://github.com/tsightler/ring-mqtt/issues?q=is%3Aissue+) for the bug you have encountered.
      options:
        - label: I have searched all existing open/closed issues
          required: true
  - type: checkboxes
    attributes:
      label: Is this really a bug?  If you don't have some way to confirm it is a bug, errors in the log, code that is clearly wrong, or at least a clear method to reproduce something that doesn't work, then it's not (yet) a bug.
      description: Support questions or functional issues without proof should be posted in the appropriate [discussion groups](https://github.com/tsightler/ring-mqtt/discussions) 
        instead.  Note that issues posted in the dicussion group may be converted to bugs once confirmed.
      options:
        - label: I'm confident this is a bug and I have logs or other data to confirm it.
          required: true
  - type: checkboxes
    attributes:
      label: Have you read and followed any recommendations in the Support and Troubleshooting section of the wiki?
      description: If your issue is covered in [the wiki](https://github.com/tsightler/ring-mqtt/discussions) please follow all steps there prior to opening an issue.
      options:
        - label: I have read the support wiki and followed any applicable steps.
          required: true
  - type: checkboxes
    attributes:
      label: Did this issue start after an upgrade? 
      description: If the issue appeared after an upgrade of ring-mqtt, please be sure to read the [release notes](https://github.com/tsightler/ring-mqtt/releases) for any mitigating information.
      options:
        - label: This not an upgrade issue or I have read the release notes and performed any applicable steps that match my issue.
          required: true
  - type: checkboxes
    attributes:
      label: Are you prepared to respond and provide all relevant information (logs, screenshots, etc)
      description: Please **DO NOT** open bugs if you are not prepared to provide logs or answer questions in a
        timely manner (at least every few days)
      options:
        - label: I am prepared to provide logs, answer questions, and respond in a reasonable timeframe.
          required: true
  - type: input
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of the issue.  Please be sure to enter brief summary of the issue in the title as well.
    validations:
      required: true
  - type: input
    attributes:
      label: Steps to Reproduce
      placeholder: Please provide the exact steps required to reproduce the behavior.  A reproducer is something that I can do to reproduce the issue, not something that doesn't work in your environment.
    validations:
      required: true
  - type: input
    attributes:
      label: Expected Behavior
      placeholder: Descibe clearly the behavior that is expected
    validations:
      required: true
  - type: textarea
    id: Logs
    attributes:
      label: Log Output
      placeholder: Please include the full ring-mqtt logs as they will be needed in almost all cases.  If you don't know how to post logs, please reconsider opening a bug as you probably don't have a bug, you have a support question.  If you decide to open an issue without providing logs, or providing only a snippet of logs, be prepared that the first response will likely be to provide full logs.  If you do not want to post full logs here due to privacy concerns, you can send them to my email using the same username (tsightler) at gmail, and reference the issue number.  If you do not know how to gather full logs for the addon see https://github.com/tsightler/ring-mqtt-ha-addon/blob/main/GET-LOGS.md
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: Config
    attributes:
      label: Config File
      placeholder: Post the contents of YAML config from HA addon or config.json file _without sensitive information_
      render: shell
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Environment
  - type: input
    attributes:
      label: Install Type
      placeholder: Home Assistant Addon, Docker, Manual
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      placeholder: v5.0.3
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      placeholder: Home Assistant OS / Ubuntu / Debian / RaspianOS / etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Architecture
      placeholder: x86_64 / arm64 / arm7 / etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Machine Details
      placeholder: Raspberry Pi / Physical x86_64 / Virtual Machine (provide hypervisor details) / etc.
    validations:
      required: true
