blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/tsightler/ring-mqtt/discussions/categories/feature-requests
    about: Please do not open issues for feature requests, use the appropriate discussion group
